// DEMO DATA — All schemes below are clearly marked sample/demo content.
// They are NOT real government schemes. "Open official website" links point to
// the real, verified Karnataka Government department/portal websites.

export interface DemoSchemeSeed {
  slug: string;
  name_kn: string;
  name_en: string;
  name_hi: string;
  desc_kn: string;
  desc_en: string;
  desc_hi: string;
  simple_kn: string;
  simple_en: string;
  simple_hi: string;
  category: string;
  department: string;
  start_date: string;
  last_date: string;
  status: 'draft' | 'published' | 'expired' | 'needs_verification';
  official_url: string;
  last_verified_at: string;
  verify_status: 'verified' | 'needs_review' | 'expired';
  view_count: number;
  tutorial_video: string | null;
  eligibility: { field: string; operator: string; value: string }[];
  documents: { name_kn: string; name_en: string; name_hi: string; desc_kn: string; desc_en: string; desc_hi: string }[];
  steps: { title_kn: string; title_en: string; title_hi: string; body_kn: string; body_en: string; body_hi: string; tip_kn: string; tip_en: string; tip_hi: string }[];
}

export const categories = [
  { slug: 'students', name_kn: 'ವಿದ್ಯಾರ್ಥಿಗಳು', name_en: 'Students', name_hi: 'विद्यार्थी', icon: '🎓', description_kn: 'ವಿದ್ಯಾರ್ಥಿ ವೇತನ ಮತ್ತು ಶೈಕ್ಷಣಿಕ ಯೋಜನೆಗಳು', description_en: 'Scholarships and educational schemes', description_hi: 'छात्रवृत्ति और शैक्षिक योजनाएँ', sort_order: 1 },
  { slug: 'women', name_kn: 'ಮಹಿಳೆಯರು', name_en: 'Women', name_hi: 'महिलाएँ', icon: '👩', description_kn: 'ಮಹಿಳಾ ಸಬಲೀಕರಣ ಮತ್ತು ಸಹಾಯ ಯೋಜನೆಗಳು', description_en: "Women's empowerment and assistance schemes", description_hi: 'महिला सशक्तिकरण और सहायता योजनाएँ', sort_order: 2 },
  { slug: 'farmers', name_kn: 'ರೈತರು', name_en: 'Farmers', name_hi: 'किसान', icon: '🌾', description_kn: 'ಕೃಷಿ ಮತ್ತು ರೈತ ಪ್ರಯೋಜನ ಯೋಜನೆಗಳು', description_en: 'Agriculture and farmer benefit schemes', description_hi: 'कृषि और किसान लाभ योजनाएँ', sort_order: 3 },
  { slug: 'employment', name_kn: 'ಉದ್ಯೋಗ', name_en: 'Employment', name_hi: 'रोज़गार', icon: '💼', description_kn: 'ಉದ್ಯೋಗ ಮತ್ತು ತರಬೇತಿ ಯೋಜನೆಗಳು', description_en: 'Employment and training schemes', description_hi: 'रोज़गार और प्रशिक्षण योजनाएँ', sort_order: 4 },
  { slug: 'housing', name_kn: 'ವಸತಿ', name_en: 'Housing', name_hi: 'आवास', icon: '🏠', description_kn: 'ಮನೆ ನಿರ್ಮಾಣ ಮತ್ತು ವಸತಿ ಸಹಾಯ', description_en: 'Home construction and housing assistance', description_hi: 'मकान निर्माण और आवास सहायता', sort_order: 5 },
  { slug: 'health', name_kn: 'ಆರೋಗ್ಯ', name_en: 'Health', name_hi: 'स्वास्थ्य', icon: '🏥', description_kn: 'ಆರೋಗ್ಯ ವಿಮೆ ಮತ್ತು ಚಿಕಿತ್ಸಾ ಸಹಾಯ', description_en: 'Health insurance and treatment assistance', description_hi: 'स्वास्थ्य बीमा और उपचार सहायता', sort_order: 6 },
  { slug: 'disability', name_kn: 'ವಿಕಲಚೇತನಿಗಳು', name_en: 'Persons with Disabilities', name_hi: 'दिव्यांगजन', icon: '♿', description_kn: 'ವಿಕಲಚೇತನ ಸಹಾಯ ಯೋಜನೆಗಳು', description_en: 'Disability assistance schemes', description_hi: 'दिव्यांगता सहायता योजनाएँ', sort_order: 7 },
  { slug: 'senior-citizens', name_kn: 'ಹಿರಿಯ ನಾಗರಿಕರು', name_en: 'Senior Citizens', name_hi: 'वरिष्ठ नागरिक', icon: '👴', description_kn: 'ವೃದ್ಧಾಪ್ಯ ಮತ್ತು ಹಿರಿಯರ ಪಿಂಚಣಿ', description_en: 'Old age pensions and senior benefits', description_hi: 'वृद्धावस्था पेंशन और वरिष्ठ लाभ', sort_order: 8 },
  { slug: 'financial', name_kn: 'ಆರ್ಥಿಕ ಸಹಾಯ', name_en: 'Financial Assistance', name_hi: 'वित्तीय सहायता', icon: '💰', description_kn: 'ನೇರ ಆರ್ಥಿಕ ಸಹಾಯ ಯೋಜನೆಗಳು', description_en: 'Direct financial assistance schemes', description_hi: 'प्रत्यक्ष वित्तीय सहायता योजनाएँ', sort_order: 9 },
  { slug: 'business', name_kn: 'ವ್ಯಾಪಾರ ಮತ್ತು ಸ್ವರೋಜಗಾರ', name_en: 'Business & Self Employment', name_hi: 'व्यापार और स्वरोज़गार', icon: '🏢', description_kn: 'ಸ್ವರೋಜಗಾರ ಮತ್ತು ಸಣ್ಣ ಉದ್ಯಮ ಯೋಜನೆಗಳು', description_en: 'Self-employment and small business schemes', description_hi: 'स्वरोज़गार और लघु उद्यम योजनाएँ', sort_order: 10 },
];

export const departments = [
  { slug: 'public-instruction', name_kn: 'ಶಿಕ್ಷಣ ಇಲಾಖೆ', name_en: 'Department of Public Instruction', name_hi: 'लोक शिक्षा विभाग' },
  { slug: 'agriculture', name_kn: 'ಕೃಷಿ ಇಲಾಖೆ', name_en: 'Department of Agriculture', name_hi: 'कृषि विभाग' },
  { slug: 'women-child', name_kn: 'ಮಹಿಳಾ ಮತ್ತು ಮಕ್ಕಳ ಅಭಿವೃದ್ಧಿ ಇಲಾಖೆ', name_en: 'Women & Child Development Department', name_hi: 'महिला एवं बाल विकास विभाग' },
  { slug: 'housing-board', name_kn: 'ವಸತಿ ಮಂಡಳಿ', name_en: 'Karnataka Housing Board', name_hi: 'आवास बोर्ड' },
  { slug: 'health-family-welfare', name_kn: 'ಆರೋಗ್ಯ ಮತ್ತು ಕುಟುಂಬ ಕಲ್ಯಾಣ ಇಲಾಖೆ', name_en: 'Health & Family Welfare Department', name_hi: 'स्वास्थ्य एवं परिवार कल्याण विभाग' },
  { slug: 'social-welfare', name_kn: 'ಸಮಾಜ ಕಲ್ಯಾಣ ಇಲಾಖೆ', name_en: 'Department of Social Welfare', name_hi: 'सामाजिक कल्याण विभाग' },
  { slug: 'labour', name_kn: 'ಕಾರ್ಮಿಕ ಇಲಾಖೆ', name_en: 'Department of Labour', name_hi: 'श्रम विभाग' },
  { slug: 'skill-development', name_kn: 'ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿ ಇಲಾಖೆ', name_en: 'Department of Skill Development', name_hi: 'कौशल विकास विभाग' },
  { slug: 'energy', name_kn: 'ವಿದ್ಯುತ್ ಇಲಾಖೆ', name_en: 'Department of Energy', name_hi: 'ऊर्जा विभाग' },
  { slug: 'msme', name_kn: 'ಕಿರು ಮತ್ತು ಅಂಗಡಿ ಉದ್ಯಮಗಳ ಇಲಾಖೆ', name_en: 'Department of MSME', name_hi: 'सूक्ष्म, लघु एवं मध्यम उद्यम विभाग' },
];

// Verified (HTTP 200) real Karnataka Government portals, mapped by department.
// Demo schemes link to the department/portal a real applicant would visit.
export const OFFICIAL_PORTALS: Record<string, string> = {
  'public-instruction': 'https://dce.karnataka.gov.in',
  'agriculture': 'https://sevasindhu.karnataka.gov.in',
  'women-child': 'https://wcd.karnataka.gov.in',
  'housing-board': 'https://khb.karnataka.gov.in',
  'health-family-welfare': 'https://nhm.karnataka.gov.in',
  'social-welfare': 'https://sevasindhu.karnataka.gov.in',
  'labour': 'https://labour.karnataka.gov.in',
  'skill-development': 'https://sevasindhu.karnataka.gov.in',
  'energy': 'https://kptcl.karnataka.gov.in',
  'msme': 'https://sevasindhu.karnataka.gov.in',
};

// Per-scheme portal overrides (all verified HTTP 200, root URLs only).
// Spreads demo schemes across real portals instead of one catch-all.
export const PORTAL_OVERRIDES: Record<string, string> = {
  // Karnataka One — citizen e-services (pensions, registrations, applications)
  'farmer-pension-2026': 'https://karnatakaone.gov.in',
  'old-age-pension-2026': 'https://karnatakaone.gov.in',
  'additional-old-age-pension-2026': 'https://karnatakaone.gov.in',
  'family-crisis-support-2026': 'https://karnatakaone.gov.in',
  'emergency-financial-assistance-2026': 'https://karnatakaone.gov.in',
  'shop-registration-support-2026': 'https://karnatakaone.gov.in',
  'street-vendor-vending-2026': 'https://karnatakaone.gov.in',
  'debt-relief-poor-families-2026': 'https://karnatakaone.gov.in',
  'education-loan-guarantee-2026': 'https://karnatakaone.gov.in',
  'disability-marriage-incentive-2026': 'https://karnatakaone.gov.in',
  'household-savings-incentive-2026': 'https://karnatakaone.gov.in',
  // Revenue department — land records, disaster relief, urban development
  'disaster-relief-cash-2026': 'https://revenue.karnataka.gov.in',
  'slum-area-development-2026': 'https://revenue.karnataka.gov.in',
  'crop-loan-waiver-2026': 'https://revenue.karnataka.gov.in',
  // RDPR — rural development & panchayat raj
  'cold-storage-assistance-2026': 'https://rdpr.karnataka.gov.in',
  'farm-machinery-rental-2026': 'https://rdpr.karnataka.gov.in',
  'dairy-farming-support-2026': 'https://rdpr.karnataka.gov.in',
  'livelihood-cash-support-2026': 'https://rdpr.karnataka.gov.in',
  // State portal — flagship / informational schemes
  'student-digital-literacy-2026': 'https://karnataka.gov.in',
  'senior-digital-literacy-2026': 'https://karnataka.gov.in',
  'sign-language-training-2026': 'https://karnataka.gov.in',
  'senior-life-insurance-2026': 'https://karnataka.gov.in',
  'export-promotion-grant-2026': 'https://karnataka.gov.in',
  'competitive-exam-coaching-2026': 'https://karnataka.gov.in',
  'disability-education-support-2026': 'https://karnataka.gov.in',
  // Women & Child Development — women, disability & senior citizen schemes
  'girl-child-savings-2026': 'https://wcd.karnataka.gov.in',
  'women-skill-livelihood-2026': 'https://wcd.karnataka.gov.in',
  'women-entrepreneur-microloan-2026': 'https://wcd.karnataka.gov.in',
  'wheelchair-subsidy-2026': 'https://wcd.karnataka.gov.in',
  'assistive-devices-subsidy-2026': 'https://wcd.karnataka.gov.in',
  'disability-allowance-2026': 'https://wcd.karnataka.gov.in',
  'disability-caregiver-allowance-2026': 'https://wcd.karnataka.gov.in',
  'senior-companion-support-2026': 'https://wcd.karnataka.gov.in',
  'assisted-living-grant-2026': 'https://wcd.karnataka.gov.in',
  'senior-day-care-centres-2026': 'https://wcd.karnataka.gov.in',
};

export const D = {
  aadhaar: { name_kn: 'ಆಧಾರ್ ಕಾರ್ಡ್', name_en: 'Aadhaar Card', name_hi: 'आधार कार्ड', desc_kn: 'ಸರ್ಕಾರಿ ಗುರುತಿನ ದಾಖಲೆಯಾಗಿ ಆಧಾರ್ ಕಾರ್ಡ್ ಕಡ್ಡಾಯ.', desc_en: 'Aadhaar card is mandatory as a government ID proof.', desc_hi: 'सरकारी पहचान प्रमाण के रूप में आधार कार्ड अनिवार्य है।' },
  income: { name_kn: 'ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ', name_en: 'Income Certificate', name_hi: 'आय प्रमाणपत्र', desc_kn: 'ತಹಸೀಲ್ದಾರ್‌ನಿಂದ ವಾರ್ಷಿಕ ಕುಟುಂಬ ಆದಾಯ ದೃಢೀಕರಣ.', desc_en: 'Annual family income certificate issued by the Tahsildar.', desc_hi: 'तहसीलदार द्वारा जारी वार्षिक पारिवारिक आय प्रमाणपत्र।' },
  caste: { name_kn: 'ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ', name_en: 'Caste Certificate', name_hi: 'जाति प्रमाणपत्र', desc_kn: 'ಅನ್ವಯವಾದರೆ ಜಾತಿ/ಮೀಸಲಾತಿ ವರ್ಗ ದಾಖಲೆ.', desc_en: 'Caste/reservation category certificate, if applicable.', desc_hi: 'लागू होने पर जाति/आरक्षण श्रेणी प्रमाणपत्र।' },
  bank: { name_kn: 'ಬ್ಯಾಂಕ್ ಪಾಸ್‌ಬುಕ್', name_en: 'Bank Passbook', name_hi: 'बैंक पासबुक', desc_kn: 'ಹಣ ವರ್ಗಾವಣೆಗಾಗಿ ನಿಮ್ಮ ಹೆಸರಿನಲ್ಲಿ ಸಕ್ರಿಯ ಬ್ಯಾಂಕ್ ಖಾತೆ.', desc_en: 'Active bank account in your name for fund transfer.', desc_hi: 'धन हस्तांतरण के लिए आपके नाम पर सक्रिय बैंक खाता।' },
  marks: { name_kn: 'ಅಂಕಪಟ್ಟಿ', name_en: 'Marks Card', name_hi: 'अंक पत्र', desc_kn: 'ಕೊನೆಯ ಶೈಕ್ಷಣಿಕ ವರ್ಷದ ಅಂಕಪಟ್ಟಿ.', desc_en: 'Marks card of the last academic year.', desc_hi: 'पिछले शैक्षिक वर्ष का अंक पत्र।' },
  collegeId: { name_kn: 'ಕಾಲೇಜ್ ಗುರುತಿನ ಚೀಟಿ', name_en: 'College ID', name_hi: 'कॉलेज पहचान पत्र', desc_kn: 'ಸಕ್ರಿಯ ಕಾಲೇಜ್/ಸಂಸ್ಥೆಯ ಗುರುತಿನ ಚೀಟಿ.', desc_en: 'Active college/institution identity card.', desc_hi: 'सक्रिय कॉलेज/संस्थान का पहचान पत्र।' },
  photo: { name_kn: 'ಪಾಸ್‌ಪೋರ್ಟ್ ಗಾತ್ರದ ಫೋಟೋ', name_en: 'Passport-size Photograph', name_hi: 'पासपोर्ट आकार फोटो', desc_kn: 'ಇತ್ತೀಚಿನ ಬಿಳಿ ಹಿನ್ನೆಲೆಯ ಫೋಟೋ.', desc_en: 'Recent photograph with a white background.', desc_hi: 'सफेद पृष्ठभूमि की हालिया फोटो।' },
  residence: { name_kn: 'ವಾಸಸ್ಥಳ ಪ್ರಮಾಣಪತ್ರ', name_en: 'Residence Certificate', name_hi: 'निवास प्रमाणपत्र', desc_kn: 'ಕರ್ನಾಟಕದ ಖಾಯಂ ನಿವಾಸಿ ಎಂದು ದೃಢೀಕರಣ.', desc_en: 'Proof of being a permanent resident of Karnataka.', desc_hi: 'कर्नाटक का स्थायी निवासी होने का प्रमाण।' },
  land: { name_kn: 'ಭೂಮಿ ದಾಖಲೆಗಳು', name_en: 'Land Records', name_hi: 'भूमि अभिलेख', desc_kn: 'ಖತಾನಿ/ಆರ್‌ಟಿಸಿ ಪ್ರತಿ, ಭೂಮಿಯ ವಿವರ.', desc_en: 'Khatauni/RTC copy with land details.', desc_hi: 'खतौनी/आरटीसी प्रति, भूमि का विवरण।' },
  ration: { name_kn: 'ರೇಷನ್ ಕಾರ್ಡ್', name_en: 'Ration Card', name_hi: 'राशन कार्ड', desc_kn: 'ಕುಟುಂಬದ ಸದಸ್ಯರ ವಿವರ ಹೊಂದಿರುವ ರೇಷನ್ ಕಾರ್ಡ್.', desc_en: 'Ration card with family member details.', desc_hi: 'परिवार के सदस्यों का विवरण रखने वाला राशन कार्ड।' },
  disabilityCert: { name_kn: 'ವಿಕಲಚೇತನ ಪ್ರಮಾಣಪತ್ರ', name_en: 'Disability Certificate', name_hi: 'दिव्यांगता प्रमाणपत्र', desc_kn: 'ಸಕ್ರಿಯ ವಿಕಲಚೇತನ ಪ್ರಮಾಣಪತ್ರ (40% ಮತ್ತು ಮೇಲಿನ ಅಂಗವೈಕಲ್ಯ).', desc_en: 'Valid disability certificate (40% and above).', desc_hi: 'वैध दिव्यांगता प्रमाणपत्र (40% या अधिक)।' },
  pensionBook: { name_kn: 'ಪಿಂಚಣಿ ಪುಸ್ತಕ', name_en: 'Pension Book', name_hi: 'पेंशन पुस्तिका', desc_kn: 'ಹಳೆಯ ಪಿಂಚಣಿ ಪುಸ್ತಕ ಇದ್ದರೆ ಸಂಲಗ್ನಗೊಳಿಸಿ.', desc_en: 'Attach previous pension book, if available.', desc_hi: 'पिछली पेंशन पुस्तिका उपलब्ध हो तो संलग्न करें।' },
};

export const stepBase = (scheme_kn: string, scheme_en: string, scheme_hi: string) => [
  { title_kn: 'ಅಧಿಕೃತ ಅರ್ಜಿ ವೆಬ್‌ಸೈಟ್ ತೆರೆಯಿರಿ', title_en: 'Open the official application website', title_hi: 'अधिकृत आवेदन वेबसाइट खोलें',
    body_kn: 'ಕೆಳಗಿನ "ಅಧಿಕೃತ ವೆಬ್‌ಸೈಟ್ ತೆರೆಯಿರಿ" ಬಟನ್ ಬಳಸಿ ಸರ್ಕಾರಿ ಪೋರ್ಟಲ್ ತೆರೆಯಿರಿ.', body_en: 'Use the "Open Official Website" button below to open the government portal.',
    body_hi: 'नीचे "आधिकारिक वेबसाइट खोलें" बटन का उपयोग करके सरकारी पोर्टल खोलें।',
    tip_kn: '"ಅಧಿಕೃತ ವೆಬ್‌ಸೈಟ್ ತೆರೆಯಿರಿ" ಕೊಂಡಿ ಸಂಬಂಧಪಟ್ಟ ಇಲಾಖೆಯ ನಿಜವಾದ ಸರ್ಕಾರಿ ಪೋರ್ಟಲ್ ತೆರೆಯುತ್ತದೆ.', tip_en: 'The "Open Official Website" link opens the real government portal of the concerned department.',
    tip_hi: '"आधिकारिक वेबसाइट खोलें" लिंक संबंधित विभाग का वास्तविक सरकारी पोर्टल खोलता है।' },
  { title_kn: 'ಖಾತೆ ರಚಿಸಿ ಅಥವಾ ಲಾಗಿನ್ ಮಾಡಿ', title_en: 'Create an account or log in', title_hi: 'खाता बनाएँ या लॉगिन करें',
    body_kn: 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಅಥವಾ ಇಮೇಲ್ ಬಳಸಿ ಖಾತೆ ರಚಿಸಿ.', body_en: 'Create an account using your mobile number or email.',
    body_hi: 'अपने मोबाइल नंबर या ईमेल से खाता बनाएँ।',
    tip_kn: 'ನಿಮ್ಮ ಒಟಿಪಿ ಯಾರಿಗೂ ಹಂಚಿಕೊಳ್ಳಬೇಡಿ.', tip_en: 'Never share your OTP with anyone.',
    tip_hi: 'अपना OTP किसी के साथ साझा न करें।' },
  { title_kn: `ಯೋಜನೆ ಆಯ್ಕೆ ಮಾಡಿ: ${scheme_kn}`, title_en: `Select the scheme: ${scheme_en}`, title_hi: `योजना चुनें: ${scheme_hi}`,
    body_kn: 'ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಸಂಬಂಧಿತ ಯೋಜನೆಯನ್ನು ಹುಡುಕಿ ಆಯ್ಕೆ ಮಾಡಿ.', body_en: 'Search for the relevant scheme on the portal and select it.',
    body_hi: 'पोर्टल पर संबंधित योजना खोजें और चुनें।',
    tip_kn: 'ಯೋಜನೆಯ ಸರಿಯಾದ ಹೆಸರು ಬಳಸಿ, ಇಲ್ಲದಿದ್ದರೆ ಯೋಜನೆ ಕಾಣಿಸದು.', tip_en: 'Use the exact scheme name or it may not appear.',
    tip_hi: 'सही योजना का नाम उपयोग करें, नहीं तो योजना दिखाई नहीं देगी।' },
  { title_kn: 'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ ನಮೂದಿಸಿ', title_en: 'Enter your personal information', title_hi: 'व्यक्तिगत जानकारी दर्ज करें',
    body_kn: 'ಹೆಸರು, ವಿಳಾಸ, ಕುಟುಂಬ ವಿವರ ಮತ್ತು ಸಂಪರ್ಕ ಮಾಹಿತಿ ನಮೂದಿಸಿ.', body_en: 'Enter name, address, family details and contact information.',
    body_hi: 'नाम, पता, पारिवारिक विवरण और संपर्क जानकारी दर्ज करें।',
    tip_kn: 'ಆಧಾರ್‌ನಲ್ಲಿರುವ ಹೆಸರು ಮತ್ತು ವಿಳಾಸದೊಂದಿಗೆ ಹೊಂದಾಣಿಕೆ ಮಾಡಿ.', tip_en: 'Match the name and address exactly as in Aadhaar.',
    tip_hi: 'आधार में मौजूद नाम और पते से मिलान करें।' },
  { title_kn: 'ಅಗತ್ಯ ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ', title_en: 'Upload the required documents', title_hi: 'आवश्यक दस्तावेज़ अपलोड करें',
    body_kn: 'ಎಲ್ಲಾ ದಾಖಲೆಗಳನ್ನು ಸ್ಪಷ್ಟ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.', body_en: 'Scan and upload all documents clearly.',
    body_hi: 'सभी दस्तावेज़ों को स्पष्ट रूप से स्कैन कर अपलोड करें।',
    tip_kn: 'PDF ಗಾತ್ರ ಮಿತಿ ಮತ್ತು ಸ್ವೀಕಾರಾರ್ಹ ಸ್ವರೂಪವನ್ನು ಮೊದಲು ಪರಿಶೀಲಿಸಿ.', tip_en: 'Check file size limits and accepted formats first.',
    tip_hi: 'फ़ाइल आकार सीमा और स्वीकार्य प्रारूप पहले जाँचें।' },
  { title_kn: 'ಅರ್ಜಿ ಪರಿಶೀಲಿಸಿ', title_en: 'Review your application', title_hi: 'आवेदन की समीक्षा करें',
    body_kn: 'ನಮೂದಿಸಿದ ಎಲ್ಲಾ ಮಾಹಿತಿ ಮತ್ತು ದಾಖಲೆಗಳನ್ನು ಎಚ್ಚರಿಕೆಯಿಂದ ಪರಿಶೀಲಿಸಿ.', body_en: 'Carefully review all entered information and documents.',
    body_hi: 'दर्ज की गई सभी जानकारी और दस्तावेज़ों को ध्यानपूर्वक जाँचें।',
    tip_kn: 'ತಪ್ಪಾದ ಮಾಹಿತಿ ಮುಂದೆ ತಿರಸ್ಕರಣೆಗೆ ಕಾರಣವಾಗಬಹುದು.', tip_en: 'Incorrect information can lead to rejection later.',
    tip_hi: 'गलत जानकारी बाद में अस्वीकृति का कारण बन सकती है।' },
  { title_kn: 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ', title_en: 'Submit the application', title_hi: 'आवेदन जमा करें',
    body_kn: 'ಎಲ್ಲಾ ವಿವರಗಳು ಸರಿಯಾಗಿವೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಂಡು ಸಲ್ಲಿಸಿ.', body_en: 'Confirm everything is correct and submit.',
    body_hi: 'सब कुछ सही है इसकी पुष्टि कर जमा करें।',
    tip_kn: 'ಸಲ್ಲಿಸಿದ ನಂತರ ಮಾಹಿತಿ ಬದಲಾಯಿಸಲಾಗದು.', tip_en: 'You cannot change details after submitting.',
    tip_hi: 'जमा करने के बाद विवरण बदल नहीं सकते।' },
  { title_kn: 'ಅರ್ಜಿ ಸಂಖ್ಯೆ ಉಳಿಸಿ', title_en: 'Save your application number', title_hi: 'आवेदन संख्या सहेजें',
    body_kn: 'ಸ್ವೀಕೃತಿ ಪುರಾವೆ ಮತ್ತು ಅರ್ಜಿ ಸಂಖ್ಯೆಯನ್ನು ಉಳಿಸಿ.', body_en: 'Save the acknowledgement receipt and application number.',
    body_hi: 'पावती रसीद और आवेदन संख्या सहेजें।',
    tip_kn: 'ಫೋಟೋ ತೆಗೆದು ಸುರಕ್ಷಿತವಾಗಿ ಇಟ್ಟುಕೊಳ್ಳಿ.', tip_en: 'Take a photo of it and keep it safe.',
    tip_hi: 'इसकी फोटो लेकर सुरक्षित रखें।' },
];

export const demoSchemes: DemoSchemeSeed[] = [
  {
    slug: 'student-scholarship-2026',
    name_kn: 'ವಿದ್ಯಾರ್ಥಿ ಪ್ರೋತ್ಸಾಹ ವೇತನ 2026',
    name_en: 'Student Encouragement Scholarship 2026',
    name_hi: 'विद्यार्थी प्रोत्साहन छात्रवृत्ति 2026',
    desc_kn: 'ಅರ್ಹ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಶೈಕ್ಷಣಿಕ ಖರ್ಚುಗಳಿಗಾಗಿ ಆರ್ಥಿಕ ಸಹಾಯ.',
    desc_en: 'Financial assistance for educational expenses for eligible students.',
    desc_hi: 'पात्र छात्रों के शैक्षिक खर्चों के लिए वित्तीय सहायता।',
    simple_kn: 'ಈ ಯೋಜನೆಯ ಮೂಲಕ ಅರ್ಹ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಶಿಕ್ಷಣಕ್ಕೆ ಸಂಬಂಧಿಸಿದ ಆರ್ಥಿಕ ಸಹಾಯ ನೀಡಲಾಗುತ್ತದೆ. ವಿದ್ಯಾರ್ಥಿ ವೇತನವು ನೇರವಾಗಿ ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಜಮಾ ಆಗುತ್ತದೆ.',
    simple_en: 'Through this scheme, eligible students receive financial assistance for education. The scholarship amount is credited directly to your bank account.',
    simple_hi: 'इस योजना के तहत पात्र छात्रों को शिक्षा से संबंधित वित्तीय सहायता दी जाती है। छात्रवृत्ति राशि सीधे आपके बैंक खाते में जमा होती है।',
    category: 'students', department: 'public-instruction',
    start_date: '2026-08-01', last_date: '2026-10-30', status: 'published',
    official_url: 'https://dce.karnataka.gov.in',
    last_verified_at: '2026-09-20', verify_status: 'verified', view_count: 4210,
    tutorial_video: 'https://example.com/tutorials/student-scholarship-2026',
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'student', operator: 'eq', value: 'true' },
      { field: 'age_max', operator: 'lte', value: '30' },
      { field: 'income_max', operator: 'lte', value: '250000' },
    ],
    documents: [D.aadhaar, D.income, D.caste, D.bank, D.marks, D.collegeId, D.photo],
    steps: stepBase('ವಿದ್ಯಾರ್ಥಿ ಪ್ರೋತ್ಸಾಹ ವೇತನ 2026', 'Student Encouragement Scholarship 2026', 'विद्यार्थी प्रोत्साहन छात्रवृत्ति 2026'),
  },
  {
    slug: 'farmer-crop-insurance-2026',
    name_kn: 'ರೈತ ಬೆಳೆ ವಿಮಾ ಸಹಾಯ ಯೋಜನೆ',
    name_en: 'Farmer Crop Insurance Assistance Scheme',
    name_hi: 'किसान फसल बीमा सहायता योजना',
    desc_kn: 'ನೈಸರ್ಗಿಕ ವಿಪತ್ತಿನಿಂದ ಬೆಳೆ ನಷ್ಟವಾದ ರೈತರಿಗೆ ವಿಮಾ ಸಹಾಯ.',
    desc_en: 'Insurance assistance for farmers who lose crops due to natural disasters.',
    desc_hi: 'प्राकृतिक आपदा से फसल खोने वाले किसानों के लिए बीमा सहायता।',
    simple_kn: 'ಬೆಳೆ ಕಟಾವಿಗೂ ಮೊದಲು ನೈಸರ್ಗಿಕ ವಿಪತ್ತು ಬಂದರೆ, ನಿಮ್ಮ ಬೆಳೆಗೆ ವಿಮಾ ಸಹಾಯ ಸಿಗುತ್ತದೆ. ಸಣ್ಣ ಮತ್ತು ಸಣ್ಣ ರೈತರಿಗೆ ಪ್ರೀಮಿಯಂ ಸಹಾಯ ಲಭ್ಯ.',
    simple_en: 'If a natural disaster strikes before harvest, you receive insurance assistance for your crop. Premium support is available for small and marginal farmers.',
    simple_hi: 'कटाई से पहले प्राकृतिक आपदा आने पर आपकी फसल के लिए बीमा सहायता मिलती है। छोटे और सीमांत किसानों के लिए प्रीमियम सहायता उपलब्ध है।',
    category: 'farmers', department: 'agriculture',
    start_date: '2026-07-15', last_date: '2026-11-15', status: 'published',
    official_url: 'https://sevasindhu.karnataka.gov.in',
    last_verified_at: '2026-09-18', verify_status: 'verified', view_count: 3890,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'farmer', operator: 'eq', value: 'true' },
      { field: 'income_max', operator: 'lte', value: '500000' },
    ],
    documents: [D.aadhaar, D.land, D.bank, D.ration, D.residence, D.photo],
    steps: stepBase('ರೈತ ಬೆಳೆ ವಿಮಾ ಸಹಾಯ ಯೋಜನೆ', 'Farmer Crop Insurance Assistance Scheme', 'किसान फसल बीमा सहायता योजना'),
  },
  {
    slug: 'women-entrepreneur-grant-2026',
    name_kn: 'ಮಹಿಳಾ ಉದ್ಯಮ ಸಹಾಯ ಯೋಜನೆ',
    name_en: 'Women Entrepreneur Grant Scheme',
    name_hi: 'महिला उद्यम सहायता योजना',
    desc_kn: 'ಸ್ವಂತ ಉದ್ಯಮ ಪ್ರಾರಂಭಿಸಲು ಮಹಿಳೆಯರಿಗೆ ಸಹಾಯ ಮತ್ತು ಸಬ್ಸಿಡಿ.',
    desc_en: 'Assistance and subsidy for women to start their own business.',
    desc_hi: 'अपना व्यवसाय शुरू करने के लिए महिलाओं को सहायता और सब्सिडी।',
    simple_kn: 'ನಿಮ್ಮ ಸಣ್ಣ ವ್ಯಾಪಾರ ಅಥವಾ ಉದ್ಯಮ ಪ್ರಾರಂಭಿಸಲು ಅಥವಾ ವಿಸ್ತರಿಸಲು ಸರ್ಕಾರದಿಂದ ಆರ್ಥಿಕ ಸಹಾಯ ಸಿಗುತ್ತದೆ. ಅರ್ಜಿ ಸಲ್ಲಿಸಿದ ನಂತರ ತರಬೇತಿ ಕೂಡ ನೀಡಲಾಗುತ್ತದೆ.',
    simple_en: 'You receive financial help from the government to start or expand a small business. Training is also provided after applying.',
    simple_hi: 'अपना छोटा व्यवसाय शुरू या बढ़ाने के लिए सरकार से वित्तीय सहायता मिलती है। आवेदन के बाद प्रशिक्षण भी दिया जाता है।',
    category: 'women', department: 'women-child',
    start_date: '2026-09-01', last_date: '2026-12-31', status: 'published',
    official_url: 'https://wcd.karnataka.gov.in',
    last_verified_at: '2026-09-22', verify_status: 'verified', view_count: 2750,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'gender', operator: 'eq', value: 'female' },
      { field: 'age_min', operator: 'gte', value: '18' },
      { field: 'income_max', operator: 'lte', value: '500000' },
    ],
    documents: [D.aadhaar, D.income, D.bank, D.residence, D.photo],
    steps: stepBase('ಮಹಿಳಾ ಉದ್ಯಮ ಸಹಾಯ ಯೋಜನೆ', 'Women Entrepreneur Grant Scheme', 'महिला उद्यम सहायता योजना'),
  },
  {
    slug: 'housing-assistance-2026',
    name_kn: 'ಗೃಹ ನಿರ್ಮಾಣ ಸಹಾಯ ಯೋಜನೆ',
    name_en: 'Housing Construction Assistance Scheme',
    name_hi: 'गृह निर्माण सहायता योजना',
    desc_kn: 'ಮನೆ ಹೊಂದಿಲ್ಲದ ಕುಟುಂಬಗಳಿಗೆ ಮನೆ ನಿರ್ಮಾಣಕ್ಕೆ ಸಹಾಯ.',
    desc_en: 'Housing construction assistance for families without a house.',
    desc_hi: 'मकान न होने वाले परिवारों के लिए गृह निर्माण सहायता।',
    simple_kn: 'ನಿಮ್ಮ ಕುಟುಂಬಕ್ಕೆ ಸ್ವಂತ ಮನೆ ಇಲ್ಲದಿದ್ದರೆ, ಮನೆ ನಿರ್ಮಾಣಕ್ಕೆ ಸರ್ಕಾರದಿಂದ ಸಹಾಯ ಧನ ನೀಡಲಾಗುತ್ತದೆ. ಹಂತ-ಹಂತವಾಗಿ ಹಣ ಬಿಡುಗಡೆಯಾಗುತ್ತದೆ.',
    simple_en: 'If your family does not own a house, the government gives financial help to build one. Funds are released in stages.',
    simple_hi: 'यदि आपके परिवार के पास अपना मकान नहीं है, तो सरकार मकान बनाने के लिए आर्थिक सहायता देती है। धनराशि चरणों में जारी होती है।',
    category: 'housing', department: 'housing-board',
    start_date: '2026-06-01', last_date: '2026-10-15', status: 'published',
    official_url: 'https://khb.karnataka.gov.in',
    last_verified_at: '2026-09-15', verify_status: 'verified', view_count: 3320,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'income_max', operator: 'lte', value: '250000' },
      { field: 'age_min', operator: 'gte', value: '21' },
    ],
    documents: [D.aadhaar, D.income, D.land, D.bank, D.ration, D.residence, D.photo],
    steps: stepBase('ಗೃಹ ನಿರ್ಮಾಣ ಸಹಾಯ ಯೋಜನೆ', 'Housing Construction Assistance Scheme', 'गृह निर्माण सहायता योजना'),
  },
  {
    slug: 'health-assistance-card-2026',
    name_kn: 'ಆರೋಗ್ಯ ಸಹಾಯ ಕಾರ್ಡ್ ಯೋಜನೆ',
    name_en: 'Health Assistance Card Scheme',
    name_hi: 'स्वास्थ्य सहायता कार्ड योजना',
    desc_kn: 'ಕುಟುಂಬದ ಆರೋಗ್ಯ ಚಿಕಿತ್ಸೆಗೆ ಆರ್ಥಿಕ ಸಹಾಯ ಮತ್ತು ಉಚಿತ ಪರೀಕ್ಷೆ.',
    desc_en: 'Financial assistance for family healthcare and free check-ups.',
    desc_hi: 'परिवार के स्वास्थ्य उपचार के लिए वित्तीय सहायता और मुफ्त जाँच।',
    simple_kn: 'ಈ ಕಾರ್ಡ್ ಇದ್ದರೆ ಕುಟುಂಬದ ಆಸ್ಪತ್ರೆ ಖರ್ಚುಗಳಿಗೆ ಸಹಾಯ ಸಿಗುತ್ತದೆ. ನಿರ್ದಿಷ್ಟ ಆಸ್ಪತ್ರೆಗಳಲ್ಲಿ ಉಚಿತ ಪರೀಕ್ಷೆ ಮತ್ತು ಚಿಕಿತ್ಸೆ ಲಭ್ಯ.',
    simple_en: 'With this card you get help with hospital expenses. Free tests and treatment are available at selected hospitals.',
    simple_hi: 'इस कार्ड से परिवार के अस्पताल खर्च में सहायता मिलती है। चयनित अस्पतालों में मुफ्त जाँच और उपचार उपलब्ध है।',
    category: 'health', department: 'health-family-welfare',
    start_date: '2026-01-01', last_date: '2026-12-31', status: 'needs_verification',
    official_url: 'https://nhm.karnataka.gov.in',
    last_verified_at: '2026-06-10', verify_status: 'needs_review', view_count: 2440,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'income_max', operator: 'lte', value: '250000' },
    ],
    documents: [D.aadhaar, D.income, D.ration, D.bank, D.photo],
    steps: stepBase('ಆರೋಗ್ಯ ಸಹಾಯ ಕಾರ್ಡ್ ಯೋಜನೆ', 'Health Assistance Card Scheme', 'स्वास्थ्य सहायता कार्ड योजना'),
  },
  {
    slug: 'disability-allowance-2026',
    name_kn: 'ವಿಕಲಚೇತನ ಸಹಾಯ ವೇತನ ಯೋಜನೆ',
    name_en: 'Disability Assistance Allowance Scheme',
    name_hi: 'दिव्यांगता सहायता भत्ता योजना',
    desc_kn: 'ದಾಖಲಿತ ವಿಕಲಚೇತನರಿಗೆ ಮಾಸಿಕ ಸಹಾಯ ವೇತನ.',
    desc_en: 'Monthly assistance allowance for persons with certified disabilities.',
    desc_hi: 'प्रमाणित दिव्यांगता वाले व्यक्तियों के लिए मासिक सहायता भत्ता।',
    simple_kn: '40% ಅಥವಾ ಅದಕ್ಕಿಂತ ಹೆಚ್ಚು ಅಂಗವೈಕಲ್ಯ ಇದ್ದರೆ, ಪ್ರತಿ ತಿಂಗಳು ಸಹಾಯ ವೇತನ ನೇರವಾಗಿ ಬ್ಯಾಂಕ್‌ಗೆ ಜಮಾ ಆಗುತ್ತದೆ.',
    simple_en: 'If you have 40% or more disability, a monthly assistance allowance is credited directly to your bank account.',
    simple_hi: 'यदि आपकी 40% या अधिक दिव्यांगता है, तो मासिक सहायता भत्ता सीधे आपके बैंक खाते में जमा होता है।',
    category: 'disability', department: 'social-welfare',
    start_date: '2026-04-01', last_date: '2026-10-31', status: 'published',
    official_url: 'https://wcd.karnataka.gov.in', last_verified_at: '2026-09-10', verify_status: 'verified', view_count: 1980,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'disability', operator: 'eq', value: 'true' },
      { field: 'age_min', operator: 'gte', value: '18' },
      { field: 'income_max', operator: 'lte', value: '500000' },
    ],
    documents: [D.aadhaar, D.disabilityCert, D.income, D.bank, D.residence, D.photo],
    steps: stepBase('ವಿಕಲಚೇತನ ಸಹಾಯ ವೇತನ ಯೋಜನೆ', 'Disability Assistance Allowance Scheme', 'दिव्यांगता सहायता भत्ता योजना'),
  },
  {
    slug: 'old-age-pension-2026',
    name_kn: 'ವೃದ್ಧಾಪ್ಯ ಪಿಂಚಣಿ ಯೋಜನೆ',
    name_en: 'Old Age Pension Scheme',
    name_hi: 'वृद्धावस्था पेंशन योजना',
    desc_kn: '60 ವರ್ಷ ಮೇಲ್ಪಟ್ಟ ಹಿರಿಯ ನಾಗರಿಕರಿಗೆ ಮಾಸಿಕ ಪಿಂಚಣಿ.',
    desc_en: 'Monthly pension for senior citizens above 60 years.',
    desc_hi: '60 वर्ष से अधिक आयु के वरिष्ठ नागरिकों के लिए मासिक पेंशन।',
    simple_kn: '60 ವರ್ಷ ಮೇಲ್ಪಟ್ಟವರಿಗೆ ಮತ್ತು ಆದಾಯ ಮಿತಿ ಒಳಗಿರುವವರಿಗೆ ಪ್ರತಿ ತಿಂಗಳು ಪಿಂಚಣಿ ಸಿಗುತ್ತದೆ. ಹಣ ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ನೇರವಾಗಿ ಜಮಾ ಆಗುತ್ತದೆ.',
    simple_en: 'If you are above 60 and within the income limit, you receive a monthly pension credited directly to your bank account.',
    simple_hi: '60 वर्ष से ऊपर और आय सीमा के भीतर होने पर हर महीने पेंशन मिलती है। राशि सीधे आपके बैंक खाते में जमा होती है।',
    category: 'senior-citizens', department: 'social-welfare',
    start_date: '2026-01-01', last_date: '2026-12-31', status: 'published',
    official_url: 'https://karnatakaone.gov.in', last_verified_at: '2026-09-21', verify_status: 'verified', view_count: 5120,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'age_min', operator: 'gte', value: '60' },
      { field: 'income_max', operator: 'lte', value: '100000' },
    ],
    documents: [D.aadhaar, D.income, D.bank, D.residence, D.pensionBook, D.photo],
    steps: stepBase('ವೃದ್ಧಾಪ್ಯ ಪಿಂಚಣಿ ಯೋಜನೆ', 'Old Age Pension Scheme', 'वृद्धावस्था पेंशन योजना'),
  },
  {
    slug: 'unemployment-allowance-2026',
    name_kn: 'ನಿರುದ್ಯೋಗ ಭತ್ಯೆ ಯೋಜನೆ',
    name_en: 'Unemployment Allowance Scheme',
    name_hi: 'बेरोज़गारी भत्ता योजना',
    desc_kn: 'ಶಿಕ್ಷಿತ ನಿರುದ್ಯೋಗಿಗಳಿಗೆ ಮಾಸಿಕ ಭತ್ಯೆ ಮತ್ತು ಉದ್ಯೋಗ ಸಂಬಂಧಿ ತರಬೇತಿ.',
    desc_en: 'Monthly allowance and job-related training for educated unemployed youth.',
    desc_hi: 'शिक्षित बेरोज़गार युवाओं के लिए मासिक भत्ता और रोज़गार संबंधी प्रशिक्षण।',
    simple_kn: 'ಉದ್ಯೋಗ ಇಲ್ಲದ ಶಿಕ್ಷಿತ ಯುವಕರಿಗೆ ಪ್ರತಿ ತಿಂಗಳು ಭತ್ಯೆ ಸಿಗುತ್ತದೆ. ಜೊತೆಗೆ ಕೌಶಲ್ಯ ತರಬೇತಿ ಮತ್ತು ಉದ್ಯೋಗ ಅವಕಾಶಗಳನ್ನು ಒದಗಿಸಲಾಗುತ್ತದೆ.',
    simple_en: 'Educated unemployed youth receive a monthly allowance, along with skill training and job opportunities.',
    simple_hi: 'रोज़गार न होने पर शिक्षित युवाओं को हर महीने भत्ता मिलता है। साथ ही कौशल प्रशिक्षण और रोज़गार के अवसर दिए जाते हैं।',
    category: 'employment', department: 'labour',
    start_date: '2026-08-15', last_date: '2026-11-30', status: 'published',
    official_url: 'https://labour.karnataka.gov.in',
    last_verified_at: '2026-09-19', verify_status: 'verified', view_count: 3010,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'employment', operator: 'eq', value: 'unemployed' },
      { field: 'age_min', operator: 'gte', value: '18' },
      { field: 'age_max', operator: 'lte', value: '35' },
      { field: 'income_max', operator: 'lte', value: '250000' },
    ],
    documents: [D.aadhaar, D.income, D.marks, D.bank, D.residence, D.photo],
    steps: stepBase('ನಿರುದ್ಯೋಗ ಭತ್ಯೆ ಯೋಜನೆ', 'Unemployment Allowance Scheme', 'बेरोज़गारी भत्ता योजना'),
  },
  {
    slug: 'self-employment-loan-2026',
    name_kn: 'ಸ್ವರೋಜಗಾರ ಸಹಾಯ ಯೋಜನೆ',
    name_en: 'Self-Employment Assistance Scheme',
    name_hi: 'स्वरोज़गार सहायता योजना',
    desc_kn: 'ಸ್ವಂತ ಕೆಲಸ ಪ್ರಾರಂಭಿಸಲು ಕಡಿಮೆ ಬಡ್ಡಿದರದ ಸಾಲ ಮತ್ತು ತರಬೇತಿ.',
    desc_en: 'Low-interest loan and training to start your own work.',
    desc_hi: 'अपना काम शुरू करने के लिए कम ब्याज पर ऋण और प्रशिक्षण।',
    simple_kn: 'ನಿಮ್ಮ ಸ್ವಂತ ವ್ಯಾಪಾರ ಅಥವಾ ಕೆಲಸ ಪ್ರಾರಂಭಿಸಲು ಸರ್ಕಾರದಿಂದ ಕಡಿಮೆ ಬಡ್ಡಿಯಲ್ಲಿ ಸಾಲ ಸಿಗುತ್ತದೆ. ಆಯ್ಕೆಯಾದವರಿಗೆ ಉಚಿತ ತರಬೇತಿ ಕೂಡ.',
    simple_en: 'The government provides a low-interest loan to start your own business or work. Selected candidates also get free training.',
    simple_hi: 'अपना व्यवसाय या काम शुरू करने के लिए सरकार से कम ब्याज पर ऋण मिलता है। चयनित उम्मीदवारों को मुफ्त प्रशिक्षण भी दी जाती है।',
    category: 'business', department: 'msme',
    start_date: '2026-07-01', last_date: '2026-10-25', status: 'published',
    official_url: 'https://sevasindhu.karnataka.gov.in',
    last_verified_at: '2026-09-17', verify_status: 'verified', view_count: 2600,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'age_min', operator: 'gte', value: '21' },
      { field: 'age_max', operator: 'lte', value: '50' },
      { field: 'income_max', operator: 'lte', value: '500000' },
    ],
    documents: [D.aadhaar, D.income, D.bank, D.residence, D.photo],
    steps: stepBase('ಸ್ವರೋಜಗಾರ ಸಹಾಯ ಯೋಜನೆ', 'Self-Employment Assistance Scheme', 'स्वरोज़गार सहायता योजना'),
  },
  {
    slug: 'farm-equipment-subsidy-2026',
    name_kn: 'ಕೃಷಿ ಯಂತ್ರೋಪಕರಣ ಸಬ್ಸಿಡಿ ಯೋಜನೆ',
    name_en: 'Farm Equipment Subsidy Scheme',
    name_hi: 'कृषि यंत्र सब्सिडी योजना',
    desc_kn: 'ರೈತರಿಗೆ ಕೃಷಿ ಯಂತ್ರೋಪಕರಣಗಳ ಖರೀದಿಗೆ ಸಬ್ಸಿಡಿ.',
    desc_en: 'Subsidy for farmers on the purchase of agricultural equipment.',
    desc_hi: 'किसानों को कृषि उपकरण खरीद पर सब्सिडी।',
    simple_kn: 'ಟ್ರ್ಯಾಕ್ಟರ್, ನೀರಿನ ಪಂಪ್ ಅಥವಾ ಇತರ ಕೃಷಿ ಯಂತ್ರಗಳ ಖರೀದಿಗೆ ಬೆಲೆಯ ಒಂದು ಭಾಗವನ್ನು ಸರ್ಕಾರ ಭರಿಸುತ್ತದೆ.',
    simple_en: 'The government pays a portion of the price when you buy a tractor, water pump or other farm machines.',
    simple_hi: 'ट्रैक्टर, पानी का पंप या अन्य कृषि यंत्र खरीदने पर सरकार कीमत का एक हिस्सा देती है।',
    category: 'farmers', department: 'agriculture',
    start_date: '2026-09-15', last_date: '2026-11-30', status: 'published',
    official_url: 'https://sevasindhu.karnataka.gov.in',
    last_verified_at: '2026-07-05', verify_status: 'needs_review', view_count: 2110,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'farmer', operator: 'eq', value: 'true' },
      { field: 'income_max', operator: 'lte', value: '500000' },
    ],
    documents: [D.aadhaar, D.land, D.bank, D.income, D.residence, D.photo],
    steps: stepBase('ಕೃಷಿ ಯಂತ್ರೋಪಕರಣ ಸಬ್ಸಿಡಿ ಯೋಜನೆ', 'Farm Equipment Subsidy Scheme', 'कृषि यंत्र सब्सिडी योजना'),
  },
  {
    slug: 'girl-education-incentive-2026',
    name_kn: 'ಹೆಣ್ಣು ಮಕ್ಕಳ ಶಿಕ್ಷಣ ಪ್ರೋತ್ಸಾಹ ಯೋಜನೆ',
    name_en: 'Girl Education Incentive Scheme',
    name_hi: 'बालिका शिक्षा प्रोत्साहन योजना',
    desc_kn: 'ಹೆಣ್ಣು ಮಕ್ಕಳ ಶಾಲಾ ಉಪಸ್ಥಿತಿ ಮತ್ತು ಉನ್ನತ ಶಿಕ್ಷಣಕ್ಕೆ ಪ್ರೋತ್ಸಾಹ.',
    desc_en: 'Incentive for girls’ school attendance and higher education.',
    desc_hi: 'बालिकाओं की स्कूल उपस्थिति और उच्च शिक्षा के लिए प्रोत्साहन।',
    simple_kn: 'ಹೆಣ್ಣು ಮಕ್ಕಳು ಶಾಲೆ ಮತ್ತು ಕಾಲೇಜಿನಲ್ಲಿ ನಿಯಮಿತವಾಗಿ ಹಾಜರಿದ್ದರೆ ಪ್ರೋತ್ಸಾಹ ಧನ ನೀಡಲಾಗುತ್ತದೆ.',
    simple_en: 'Girls who attend school and college regularly receive incentive money.',
    simple_hi: 'स्कूल और कॉलेज में नियमित उपस्थिति पर बालिकाओं को प्रोत्साहन राशि दी जाती है।',
    category: 'students', department: 'public-instruction',
    start_date: '2026-03-01', last_date: '2026-08-31', status: 'expired',
    official_url: 'https://dce.karnataka.gov.in',
    last_verified_at: '2026-09-01', verify_status: 'expired', view_count: 1750,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'gender', operator: 'eq', value: 'female' },
      { field: 'age_max', operator: 'lte', value: '25' },
      { field: 'income_max', operator: 'lte', value: '250000' },
    ],
    documents: [D.aadhaar, D.income, D.marks, D.collegeId, D.bank, D.photo],
    steps: stepBase('ಹೆಣ್ಣು ಮಕ್ಕಳ ಶಿಕ್ಷಣ ಪ್ರೋತ್ಸಾಹ ಯೋಜನೆ', 'Girl Education Incentive Scheme', 'बालिका शिक्षा प्रोत्साहन योजना'),
  },
  {
    slug: 'student-laptop-scheme-2026',
    name_kn: 'ವಿದ್ಯಾರ್ಥಿ ಲ್ಯಾಪ್‌ಟಾಪ್ ಯೋಜನೆ',
    name_en: 'Student Laptop Scheme',
    name_hi: 'विद्यार्थी लैपटॉप योजना',
    desc_kn: 'ಉನ್ನತ ಶಿಕ್ಷಣದ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಉಚಿತ ಲ್ಯಾಪ್‌ಟಾಪ್.',
    desc_en: 'Free laptop for higher education students.',
    desc_hi: 'उच्च शिक्षा के छात्रों के लिए मुफ्त लैपटॉप।',
    simple_kn: 'ಆಯ್ಕೆಯಾದ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಉಚಿತ ಲ್ಯಾಪ್‌ಟಾಪ್ ನೀಡಲಾಗುತ್ತದೆ. ಅರ್ಜಿ ಪ್ರಾರಂಭಕ್ಕೂ ಮೊದಲು ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ.',
    simple_en: 'Selected students receive a free laptop. Check eligibility before applications open.',
    simple_hi: 'चयनित छात्रों को मुफ्त लैपटॉप दिया जाता है। आवेदन शुरू होने से पहले पात्रता जाँच लें।',
    category: 'students', department: 'public-instruction',
    start_date: '2026-11-15', last_date: '2027-01-15', status: 'published',
    official_url: 'https://dce.karnataka.gov.in',
    last_verified_at: '2026-09-25', verify_status: 'verified', view_count: 1490,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'student', operator: 'eq', value: 'true' },
      { field: 'age_max', operator: 'lte', value: '26' },
      { field: 'income_max', operator: 'lte', value: '250000' },
    ],
    documents: [D.aadhaar, D.income, D.marks, D.collegeId, D.bank, D.photo],
    steps: stepBase('ವಿದ್ಯಾರ್ಥಿ ಲ್ಯಾಪ್‌ಟಾಪ್ ಯೋಜನೆ', 'Student Laptop Scheme', 'विद्यार्थी लैपटॉप योजना'),
  },
  {
    slug: 'electricity-subsidy-2026',
    name_kn: 'ವಿದ್ಯುತ್ ಸಬ್ಸಿಡಿ ಸಹಾಯ ಯೋಜನೆ',
    name_en: 'Electricity Subsidy Assistance Scheme',
    name_hi: 'बिजली सब्सिडी सहायता योजना',
    desc_kn: 'ಕಡಿಮೆ ಆದಾಯ ಕುಟುಂಬಗಳಿಗೆ ವಿದ್ಯುತ್ ಬಿಲ್ ಸಬ್ಸಿಡಿ.',
    desc_en: 'Electricity bill subsidy for low-income families.',
    desc_hi: 'कम आय वाले परिवारों के लिए बिजली बिल सब्सिडी।',
    simple_kn: 'ಕಡಿಮೆ ಆದಾಯ ಕುಟುಂಬಗಳ ವಿದ್ಯುತ್ ಬಿಲ್‌ನಲ್ಲಿ ಸರ್ಕಾರ ಸಬ್ಸಿಡಿ ನೀಡುತ್ತದೆ. ಈ ಯೋಜನೆ ಇನ್ನೂ ಡ್ರಾಫ್ಟ್ ಹಂತದಲ್ಲಿದೆ.',
    simple_en: 'The government gives a subsidy on electricity bills for low-income families. This scheme is still in draft stage.',
    simple_hi: 'कम आय वाले परिवारों के बिजली बिल पर सरकार सब्सिडी देती है। यह योजना अभी मसौदा चरण में है।',
    category: 'financial', department: 'energy',
    start_date: '2026-10-01', last_date: '2027-03-31', status: 'draft',
    official_url: 'https://kptcl.karnataka.gov.in',
    last_verified_at: '2026-09-24', verify_status: 'needs_review', view_count: 0,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'income_max', operator: 'lte', value: '100000' },
    ],
    documents: [D.aadhaar, D.income, D.ration, D.bank],
    steps: stepBase('ವಿದ್ಯುತ್ ಸಬ್ಸಿಡಿ ಸಹಾಯ ಯೋಜನೆ', 'Electricity Subsidy Assistance Scheme', 'बिजली सब्सिडी सहायता योजना'),
  },
  {
    slug: 'women-self-help-group-2026',
    name_kn: 'ಮಹಿಳಾ ಸ್ವಸಹಾಯ ಗುಂಪು ಯೋಜನೆ',
    name_en: 'Women Self-Help Group Scheme',
    name_hi: 'महिला स्वयं सहायता समूह योजना',
    desc_kn: 'ಮಹಿಳಾ ಸ್ವಸಹಾಯ ಗುಂಪುಗಳಿಗೆ ಸಾಲ ಮತ್ತು ತರಬೇತಿ ಸಹಾಯ.',
    desc_en: 'Loan and training support for women self-help groups.',
    desc_hi: 'महिला स्वयं सहायता समूहों के लिए ऋण और प्रशिक्षण सहायता।',
    simple_kn: 'ಮಹಿಳೆಯರು ಸೇರಿದ ಸ್ವಸಹಾಯ ಗುಂಪಿಗೆ ಕಡಿಮೆ ಬಡ್ಡಿಯಲ್ಲಿ ಸಾಲ ಮತ್ತು ಉಚಿತ ತರಬೇತಿ ಸಿಗುತ್ತದೆ. ಗುಂಪಿನ ಸದಸ್ಯರು ಸಣ್ಣ ಉದ್ಯಮ ಪ್ರಾರಂಭಿಸಬಹುದು.',
    simple_en: 'A women’s self-help group gets a low-interest loan and free training. Group members can start small businesses.',
    simple_hi: 'महिला स्वयं सहायता समूह को कम ब्याज पर ऋण और मुफ्त प्रशिक्षण मिलता है। समूह की सदस्य छोटा व्यवसाय शुरू कर सकती हैं।',
    category: 'women', department: 'women-child',
    start_date: '2026-05-01', last_date: '2026-12-31', status: 'published',
    official_url: 'https://wcd.karnataka.gov.in',
    last_verified_at: '2026-09-16', verify_status: 'verified', view_count: 1860,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'gender', operator: 'eq', value: 'female' },
      { field: 'age_min', operator: 'gte', value: '18' },
      { field: 'income_max', operator: 'lte', value: '300000' },
    ],
    documents: [D.aadhaar, D.income, D.bank, D.residence, D.photo],
    steps: stepBase('ಮಹಿಳಾ ಸ್ವಸಹಾಯ ಗುಂಪು ಯೋಜನೆ', 'Women Self-Help Group Scheme', 'महिला स्वयं सहायता समूह योजना'),
  },
  {
    slug: 'skill-training-stipend-2026',
    name_kn: 'ಕೌಶಲ್ಯ ತರಬೇತಿ ಭತ್ಯೆ ಯೋಜನೆ',
    name_en: 'Skill Training Stipend Scheme',
    name_hi: 'कौशल प्रशिक्षण भत्ता योजना',
    desc_kn: 'ಯುವಜನರಿಗೆ ಮಾನ್ಯತೆ ಪಡೆದ ಕೌಶಲ್ಯ ತರಬೇತಿ ಜೊತೆ ಮಾಸಿಕ ಭತ್ಯೆ.',
    desc_en: 'Monthly stipend for youth undergoing recognised skill training.',
    desc_hi: 'मान्य कौशल प्रशिक्षण लेने वाले युवाओं के लिए मासिक भत्ता।',
    simple_kn: 'ಸರ್ಕಾರ ಮಾನ್ಯತೆ ಪಡೆದ ತರಬೇತಿ ಕೇಂದ್ರಗಳಲ್ಲಿ ಕೌಶಲ್ಯ ಕಲಿಯುವಾಗ ಪ್ರತಿ ತಿಂಗಳು ಭತ್ಯೆ ಸಿಗುತ್ತದೆ. ತರಬೇತಿ ಮುಗಿದ ನಂತರ ಉದ್ಯೋಗ ಸಹಾಯ ಲಭ್ಯ.',
    simple_en: 'You get a monthly stipend while learning skills at government-recognised training centres. Placement assistance is offered after training.',
    simple_hi: 'सरकार मान्यता प्राप्त प्रशिक्षण केंद्रों में कौशल सीखते समय हर महीने भत्ता मिलता है। प्रशिक्षण के बाद प्लेसमेंट सहायता मिलती है।',
    category: 'employment', department: 'skill-development',
    start_date: '2026-06-15', last_date: '2027-02-28', status: 'published',
    official_url: 'https://sevasindhu.karnataka.gov.in',
    last_verified_at: '2026-09-12', verify_status: 'verified', view_count: 2240,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'age_min', operator: 'gte', value: '18' },
      { field: 'age_max', operator: 'lte', value: '35' },
      { field: 'income_max', operator: 'lte', value: '300000' },
    ],
    documents: [D.aadhaar, D.income, D.marks, D.bank, D.residence, D.photo],
    steps: stepBase('ಕೌಶಲ್ಯ ತರಬೇತಿ ಭತ್ಯೆ ಯೋಜನೆ', 'Skill Training Stipend Scheme', 'कौशल प्रशिक्षण भत्ता योजना'),
  },
  {
    slug: 'housing-site-allotment-2026',
    name_kn: 'ವಸತಿ ನಿವೇಶನ ಹಂಚಿಕೆ ಯೋಜನೆ',
    name_en: 'Housing Site Allotment Scheme',
    name_hi: 'आवास प्लॉट आवंटन योजना',
    desc_kn: 'ಅರ್ಹ ಕುಟುಂಬಗಳಿಗೆ ಪಟ್ಟಣದಲ್ಲಿ ವಸತಿ ನಿವೇಶನ ಹಂಚಿಕೆ.',
    desc_en: 'Allotment of residential sites in towns for eligible families.',
    desc_hi: 'पात्र परिवारों को शहर में आवासीय प्लॉट का आवंटन।',
    simple_kn: 'ಸ್ವಂತ ಮನೆ ಇಲ್ಲದ ಅರ್ಹ ಕುಟುಂಬಗಳಿಗೆ ಸರ್ಕಾರ ಪಟ್ಟಣದಲ್ಲಿ ನಿವೇಶನ ನೀಡುತ್ತದೆ. ಆಯ್ಕೆಯಾದವರು ನಿವೇಶನದಲ್ಲಿ ಮನೆ ನಿರ್ಮಿಸಬಹುದು.',
    simple_en: 'The government allots a site in the town for eligible families without their own house. Selected families can build a house on it.',
    simple_hi: 'सरकार बिना मकान वाले पात्र परिवारों को शहर में प्लॉट देती है। चयनित परिवार उस पर मकान बना सकते हैं।',
    category: 'housing', department: 'housing-board',
    start_date: '2026-04-01', last_date: '2026-12-15', status: 'published',
    official_url: 'https://khb.karnataka.gov.in',
    last_verified_at: '2026-09-08', verify_status: 'verified', view_count: 2980,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'age_min', operator: 'gte', value: '21' },
      { field: 'income_max', operator: 'lte', value: '250000' },
    ],
    documents: [D.aadhaar, D.income, D.residence, D.bank, D.ration, D.photo],
    steps: stepBase('ವಸತಿ ನಿವೇಶನ ಹಂಚಿಕೆ ಯೋಜನೆ', 'Housing Site Allotment Scheme', 'आवास प्लॉट आवंटन योजना'),
  },
  {
    slug: 'health-insurance-2026',
    name_kn: 'ಆರೋಗ್ಯ ವಿಮಾ ಯೋಜನೆ',
    name_en: 'Health Insurance Scheme',
    name_hi: 'स्वास्थ्य बीमा योजना',
    desc_kn: 'ಕುಟುಂಬದ ಆಸ್ಪತ್ರೆ ಖರ್ಚಿಗೆ ವಾರ್ಷಿಕ ವಿಮಾ ಮಿತಿ.',
    desc_en: 'Annual insurance cover for family hospital expenses.',
    desc_hi: 'परिवार के अस्पताल खर्च के लिए वार्षिक बीमा सीमा।',
    simple_kn: 'ಈ ಯೋಜನೆಯಲ್ಲಿ ಕುಟುಂಬದ ಆಸ್ಪತ್ರೆ ಖರ್ಚುಗಳಿಗೆ ವಿಮಾ ಸೌಲಭ್ಯ ಸಿಗುತ್ತದೆ. ನೋಂದಾಯಿತ ಆಸ್ಪತ್ರೆಗಳಲ್ಲಿ ನೇರ ಉಚಿತ ಚಿಕಿತ್ಸೆ ಲಭ್ಯ.',
    simple_en: 'This scheme provides insurance cover for your family’s hospital bills. Free cashless treatment is available at empanelled hospitals.',
    simple_hi: 'इस योजना में परिवार के अस्पताल बिल पर बीमा सुविधा मिलती है। सूचीबद्ध अस्पतालों में मुफ्त कैशलेस उपचार उपलब्ध है।',
    category: 'health', department: 'health-family-welfare',
    start_date: '2026-01-01', last_date: '2026-12-31', status: 'published',
    official_url: 'https://nhm.karnataka.gov.in',
    last_verified_at: '2026-09-23', verify_status: 'verified', view_count: 4120,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'income_max', operator: 'lte', value: '500000' },
    ],
    documents: [D.aadhaar, D.income, D.ration, D.bank, D.photo],
    steps: stepBase('ಆರೋಗ್ಯ ವಿಮಾ ಯೋಜನೆ', 'Health Insurance Scheme', 'स्वास्थ्य बीमा योजना'),
  },
  {
    slug: 'disability-education-support-2026',
    name_kn: 'ವಿಕಲಚೇತನ ಶಿಕ್ಷಣ ಸಹಾಯ ಯೋಜನೆ',
    name_en: 'Disability Education Support Scheme',
    name_hi: 'दिव्यांग शिक्षा सहायता योजना',
    desc_kn: 'ವಿಕಲಚೇತನ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಶುಲ್ಕ ಮತ್ತು ತರಬೇತಿ ಸಹಾಯ.',
    desc_en: 'Fee and training assistance for students with disabilities.',
    desc_hi: 'दिव्यांग छात्रों के लिए शुल्क और प्रशिक्षण सहायता।',
    simple_kn: 'ದಾಖಲಿತ ವಿಕಲಚೇತನ ವಿದ್ಯಾರ್ಥಿಗಳ ಶಾಲಾ/ಕಾಲೇಜ್ ಶುಲ್ಕ ಸರ್ಕಾರ ಭರಿಸುತ್ತದೆ. ಸಹಾಯಕ ಸಾಧನಗಳು ಮತ್ತು ತರಬೇತಿಗೆ ಹೆಚ್ಚುವರಿ ಸಹಾಯ ಲಭ್ಯ.',
    simple_en: 'The government pays school/college fees for students with certified disabilities. Extra help is available for assistive devices and training.',
    simple_hi: 'सरकार प्रमाणित दिव्यांग छात्रों की स्कूल/कॉलेज फीस भरती है। सहायक उपकरण और प्रशिक्षण के लिए अतिरिक्त सहायता मिलती है।',
    category: 'disability', department: 'social-welfare',
    start_date: '2026-06-01', last_date: '2026-12-31', status: 'published',
    official_url: 'https://karnataka.gov.in', last_verified_at: '2026-09-14', verify_status: 'verified', view_count: 1340,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'disability', operator: 'eq', value: 'true' },
      { field: 'student', operator: 'eq', value: 'true' },
      { field: 'income_max', operator: 'lte', value: '500000' },
    ],
    documents: [D.aadhaar, D.disabilityCert, D.income, D.marks, D.collegeId, D.bank, D.photo],
    steps: stepBase('ವಿಕಲಚೇತನ ಶಿಕ್ಷಣ ಸಹಾಯ ಯೋಜನೆ', 'Disability Education Support Scheme', 'दिव्यांग शिक्षा सहायता योजना'),
  },
  {
    slug: 'senior-health-care-2026',
    name_kn: 'ಹಿರಿಯರ ಆರೋಗ್ಯ ಸಂರಕ್ಷಣಾ ಯೋಜನೆ',
    name_en: 'Senior Citizens Health Care Scheme',
    name_hi: 'वरिष्ठ नागरिक स्वास्थ्य देखभाल योजना',
    desc_kn: '60 ವರ್ಷ ಮೇಲ್ಪಟ್ಟವರಿಗೆ ಉಚಿತ ಆರೋಗ್ಯ ತಪಾಸಣೆ ಮತ್ತು ಚಿಕಿತ್ಸಾ ಸಹಾಯ.',
    desc_en: 'Free health check-ups and treatment assistance for those above 60.',
    desc_hi: '60 वर्ष से अधिक आयु के लोगों के लिए मुफ्त स्वास्थ्य जाँच और उपचार सहायता।',
    simple_kn: '60 ವರ್ಷ ಮೇಲ್ಪಟ್ಟ ಹಿರಿಯ ನಾಗರಿಕರಿಗೆ ವರ್ಷಕ್ಕೊಮ್ಮೆ ಉಚಿತ ಆರೋಗ್ಯ ತಪಾಸಣೆ ಮತ್ತು ಆಸ್ಪತ್ರೆ ಖರ್ಚಿಗೆ ಸಹಾಯ ಸಿಗುತ್ತದೆ.',
    simple_en: 'Senior citizens above 60 get one free health check-up every year and help with hospital expenses.',
    simple_hi: '60 वर्ष से अधिक आयु के वरिष्ठ नागरिकों को हर साल एक मुफ्त स्वास्थ्य जाँच और अस्पताल खर्च में सहायता मिलती है।',
    category: 'senior-citizens', department: 'health-family-welfare',
    start_date: '2026-03-01', last_date: '2026-12-31', status: 'published',
    official_url: 'https://nhm.karnataka.gov.in',
    last_verified_at: '2026-09-11', verify_status: 'verified', view_count: 2670,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'age_min', operator: 'gte', value: '60' },
    ],
    documents: [D.aadhaar, D.residence, D.bank, D.pensionBook, D.photo],
    steps: stepBase('ಹಿರಿಯರ ಆರೋಗ್ಯ ಸಂರಕ್ಷಣಾ ಯೋಜನೆ', 'Senior Citizens Health Care Scheme', 'वरिष्ठ नागरिक स्वास्थ्य देखभाल योजना'),
  },
  {
    slug: 'emergency-financial-assistance-2026',
    name_kn: 'ತುರ್ತು ಆರ್ಥಿಕ ಸಹಾಯ ಯೋಜನೆ',
    name_en: 'Emergency Financial Assistance Scheme',
    name_hi: 'आपातकालीन वित्तीय सहायता योजना',
    desc_kn: 'ಅನಿರೀಕ್ಷಿತ ವಿಪತ್ತು ಅಥವಾ ತುರ್ತು ಸ್ಥಿತಿಯಲ್ಲಿ ತಕ್ಷಣ ಆರ್ಥಿಕ ಸಹಾಯ.',
    desc_en: 'Immediate financial help during unforeseen disasters or emergencies.',
    desc_hi: 'अप्रत्याशित आपदा या आपात स्थिति में तत्काल वित्तीय सहायता।',
    simple_kn: 'ಪ್ರಾಕೃತಿಕ ವಿಪತ್ತು, ಅನಾರೋಗ್ಯ ಅಥವಾ ತುರ್ತು ಸಂದರ್ಭದಲ್ಲಿ ಒಮ್ಮೆಯ ಆರ್ಥಿಕ ಸಹಾಯ ದೊರೆಯುತ್ತದೆ. ಅರ್ಜಿ ಸಲ್ಲಿಸಿದ ಕೆಲವೇ ದಿನಗಳಲ್ಲಿ ಹಣ ಜಮಾ ಆಗುತ್ತದೆ.',
    simple_en: 'You receive one-time financial help during natural disasters, illness or emergencies. Money is credited within days of applying.',
    simple_hi: 'प्राकृतिक आपदा, बीमारी या आपात स्थिति में एकमुश्त वित्तीय सहायता मिलती है। आवेदन के कुछ दिनों में पैसा जमा होता है।',
    category: 'financial', department: 'social-welfare',
    start_date: '2026-01-01', last_date: '2026-12-31', status: 'published',
    official_url: 'https://karnatakaone.gov.in', last_verified_at: '2026-09-19', verify_status: 'verified', view_count: 3450,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'income_max', operator: 'lte', value: '250000' },
    ],
    documents: [D.aadhaar, D.income, D.bank, D.ration, D.residence, D.photo],
    steps: stepBase('ತುರ್ತು ಆರ್ಥಿಕ ಸಹಾಯ ಯೋಜನೆ', 'Emergency Financial Assistance Scheme', 'आपातकालीन वित्तीय सहायता योजना'),
  },
  {
    slug: 'livelihood-cash-support-2026',
    name_kn: 'ಜೀವನೋಪಾಯ ನಗದು ಸಹಾಯ ಯೋಜನೆ',
    name_en: 'Livelihood Cash Support Scheme',
    name_hi: 'जीविका नकद सहायता योजना',
    desc_kn: 'ದಿನಗೂಲಿ ಮತ್ತು ಬಡ ಕುಟುಂಬಗಳಿಗೆ ಮಾಸಿಕ ನಗದು ಬೆಂಬಲ.',
    desc_en: 'Monthly cash support for daily-wage and poor families.',
    desc_hi: 'रोज़मज़दूर और गरीब परिवारों के लिए मासिक नकद समर्थन।',
    simple_kn: 'ಆದಾಯ ಕಡಿಮೆಯಾದ ಸಂದರ್ಭದಲ್ಲಿ ಕುಟುಂಬಕ್ಕೆ ಪ್ರತಿ ತಿಂಗಳು ನಿಗದಿತ ನಗದು ಸಹಾಯ ಬ್ಯಾಂಕ್‌ಗೆ ಜಮಾ ಆಗುತ್ತದೆ.',
    simple_en: 'When income falls, a fixed monthly cash support is credited to your family’s bank account.',
    simple_hi: 'आय घटने पर परिवार के बैंक खाते में हर महीने निश्चित नकद सहायता जमा होती है।',
    category: 'financial', department: 'social-welfare',
    start_date: '2026-07-01', last_date: '2027-03-31', status: 'published',
    official_url: 'https://rdpr.karnataka.gov.in', last_verified_at: '2026-09-05', verify_status: 'verified', view_count: 2890,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'income_max', operator: 'lte', value: '150000' },
    ],
    documents: [D.aadhaar, D.income, D.bank, D.ration, D.residence, D.photo],
    steps: stepBase('ಜೀವನೋಪಾಯ ನಗದು ಸಹಾಯ ಯೋಜನೆ', 'Livelihood Cash Support Scheme', 'जीविका नकद सहायता योजना'),
  },
  {
    slug: 'msme-startup-grant-2026',
    name_kn: 'ಎಂಎಸ್‌ಎಮ್‌ಇ ಸ್ಟಾರ್ಟಪ್ ಗ್ರಾಂಟ್ ಯೋಜನೆ',
    name_en: 'MSME Startup Grant Scheme',
    name_hi: 'एमएसएमई स्टार्टअप अनुदान योजना',
    desc_kn: 'ಹೊಸ ಸಣ್ಣ ಉದ್ಯಮ ಪ್ರಾರಂಭಿಸಲು ಮುಂಗಡ ಗ್ರಾಂಟ್.',
    desc_en: 'Upfront grant to start a new small business.',
    desc_hi: 'नया छोटा व्यवसाय शुरू करने के लिए अग्रिम अनुदान।',
    simple_kn: 'ಹೊಸ ಸಣ್ಣ ಉದ್ಯಮ ಪ್ರಾರಂಭಿಸುವವರಿಗೆ ಸಾಲದ ಜೊತೆಗೆ ಮುಂಗಡ ಗ್ರಾಂಟ್ ಸಿಗುತ್ತದೆ. ತರಬೇತಿ ಮತ್ತು ಮಾರ್ಗದರ್ಶನ ಕೂಡ ಒದಗಿಸಲಾಗುತ್ತದೆ.',
    simple_en: 'New small business starters get an upfront grant along with the loan. Training and mentoring are also provided.',
    simple_hi: 'नया छोटा व्यवसाय शुरू करने वालों को ऋण के साथ अग्रिम अनुदान मिलता है। प्रशिक्षण और मार्गदर्शन भी दिया जाता है।',
    category: 'business', department: 'msme',
    start_date: '2026-08-01', last_date: '2027-01-31', status: 'published',
    official_url: 'https://sevasindhu.karnataka.gov.in',
    last_verified_at: '2026-09-21', verify_status: 'verified', view_count: 1920,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'age_min', operator: 'gte', value: '18' },
      { field: 'age_max', operator: 'lte', value: '45' },
      { field: 'income_max', operator: 'lte', value: '500000' },
    ],
    documents: [D.aadhaar, D.income, D.bank, D.residence, D.photo],
    steps: stepBase('ಎಂಎಸ್‌ಎಮ್‌ಇ ಸ್ಟಾರ್ಟಪ್ ಗ್ರಾಂಟ್ ಯೋಜನೆ', 'MSME Startup Grant Scheme', 'एमएसएमई स्टार्टअप अनुदान योजना'),
  },
  {
    slug: 'fee-reimbursement-2026',
    name_kn: 'ಶುಲ್ಕ ಪ್ರತಿಪಾವನಿ ಯೋಜನೆ',
    name_en: 'Fee Reimbursement Scheme',
    name_hi: 'शुल्क प्रतिपूर्ति योजना',
    desc_kn: 'ಅರ್ಹ ವಿದ್ಯಾರ್ಥಿಗಳ ಕಾಲೇಜ್ ಶುಲ್ಕ ಹಿಂಪಾವನಿ.',
    desc_en: 'Reimbursement of college fees for eligible students.',
    desc_hi: 'पात्र छात्रों की कॉलेज फीस की प्रतिपूर्ति।',
    simple_kn: 'ಆಯ್ಕೆಯಾದ ವಿದ್ಯಾರ್ಥಿಗಳ ಕಾಲೇಜ್ ಶುಲ್ಕವನ್ನು ಸರ್ಕಾರ ಹಿಂಪಾವನಿ ಮಾಡುತ್ತದೆ. ಶುಲ್ಕ ರಸೀದಿ ಕಡ್ಡಾಯವಾಗಿ ಸಲ್ಲಿಸಬೇಕು.',
    simple_en: 'The government reimburses college fees for selected students. Submitting the fee receipt is mandatory.',
    simple_hi: 'सरकार चयनित छात्रों की कॉलेज फीस की प्रतिपूर्ति करती है। फीस रसीद जमा करना अनिवार्य है।',
    category: 'students', department: 'public-instruction',
    start_date: '2026-07-01', last_date: '2026-12-31', status: 'published',
    official_url: 'https://dce.karnataka.gov.in',
    last_verified_at: '2026-09-17', verify_status: 'verified', view_count: 2440,
    tutorial_video: null,
    eligibility: [
      { field: 'residency', operator: 'eq', value: 'true' },
      { field: 'student', operator: 'eq', value: 'true' },
      { field: 'age_max', operator: 'lte', value: '30' },
      { field: 'income_max', operator: 'lte', value: '350000' },
    ],
    documents: [D.aadhaar, D.income, D.marks, D.collegeId, D.bank, D.photo],
    steps: stepBase('ಶುಲ್ಕ ಪ್ರತಿಪಾವನಿ ಯೋಜನೆ', 'Fee Reimbursement Scheme', 'शुल्क प्रतिपूर्ति योजना'),
  },
];

// All 31 districts of Karnataka, in the same order across the three languages.
export const districts_kn = [
  'ಬೆಂಗಳೂರು ನಗರ', 'ಬೆಂಗಳೂರು ಗ್ರಾಮಾಂತರ', 'ಮೈಸೂರು', 'ಹುಬ್ಬಳ್ಳಿ-ಧಾರವಾಡ', 'ಮಂಗಳೂರು',
  'ಬಳ್ಳಾರಿ', 'ಬೆಳಗಾವಿ', 'ವಿಜಯಪುರ', 'ಕಲಬುರಗಿ', 'ತುಮಕೂರು', 'ಶಿವಮೊಗ್ಗ', 'ರಾಯಚೂರು',
  'ಉಡುಪಿ', 'ಹಾಸನ', 'ಮಂಡ್ಯ', 'ಗದಗ', 'ಕೊಪ್ಪಳ', 'ಬೀದರ್', 'ಚಿಕ್ಕಮಗಳೂರು', 'ಕೊಡಗು',
  'ಬಾಗಲಕೋಟೆ', 'ಚಾಮರಾಜನಗರ', 'ಚಿಕ್ಕಬಳ್ಳಾಪುರ', 'ಚಿತ್ರದುರ್ಗ', 'ದಾವಣಗೆರೆ', 'ಹಾವೇರಿ',
  'ಕೋಲಾರ', 'ರಾಮನಗರ', 'ಉತ್ತರ ಕನ್ನಡ', 'ವಿಜಯನಗರ', 'ಯಾದಗಿರಿ',
];
export const districts_hi = [
  'बेंगलुरु नगर', 'बेंगलुरु ग्रामीण', 'मैसूर', 'हुब्बली-धारवाड़', 'मंगलूर',
  'बल्लारी', 'बेलगावी', 'विजयपुर', 'कलबुरगी', 'तुमकूर', 'शिवमोग्गा', 'रायचूर',
  'उडुपी', 'हासन', 'मंड्या', 'गदग', 'कोप्पल', 'बीदर', 'चिक्कमगलुरु', 'कोडगु',
  'बागलकोट', 'चामराजनगर', 'चिक्कबल्लापुर', 'चित्रदुर्ग', 'दावणगेरे', 'हावेरी',
  'कोलार', 'रामनगर', 'उत्तर कन्नड़', 'विजयनगर', 'यादगिरि',
];
export const districts_en = [
  'Bengaluru City', 'Bengaluru Rural', 'Mysuru', 'Hubballi-Dharwad', 'Mangaluru',
  'Ballari', 'Belagavi', 'Vijayapura', 'Kalaburagi', 'Tumakuru', 'Shivamogga', 'Raichur',
  'Udupi', 'Hassan', 'Mandya', 'Gadag', 'Koppal', 'Bidar', 'Chikkamagaluru', 'Kodagu',
  'Bagalkote', 'Chamarajanagar', 'Chikkaballapur', 'Chitradurga', 'Davanagere', 'Haveri',
  'Kolar', 'Ramanagara', 'Uttara Kannada', 'Vijayanagara', 'Yadgir',
];
